### ISSUE TITLE
Support for different Allied Operation enemy levels per server

### ISSUE THREAD

**Issue by VRC-INYO** [SchaleDB/SchaleDB#30]
In global branch, they are LV80 instead of 90 ( tested by use both LV80 and LV85 student to get hit by Hyper Spiral Glare Beam from PERORODZILLA ).

**Comment by lonqie** [comment]
Thanks for bringing that to my attention, since the event has now ended and chroma bosses are unlikely to be rerun I won't make any changes at this time

If differences in levels or stats come up in future world raids between the two servers I will revisit this issue and add separate boss levels per server

**Comment by lonqie** [comment]
Reopening as I will address this since it may become an issue for the future Allied Operation raids on the CN server
