### ISSUE TITLE
Some issues about students' information

### ISSUE THREAD

**Issue by clufox37** [SchaleDB/SchaleDB#72]
![Screenshot_2024 05 01_14 06 21 095](https://github.com/SchaleDB/SchaleDB/assets/52343362/c4583d88-b595-47cd-b744-f7e529019c8f)

![캡처_2024_05_01_14_09_21_495](https://github.com/SchaleDB/SchaleDB/assets/52343362/f246d984-698e-46c7-b9b8-eb0a212ccdaf)

1. Misaka Mikoto and Shokuhou Misaki's shield mark
They can take cover, but shield mark on their weapon type is missing.

![캡처_2024_05_01_15_17_49_544](https://github.com/SchaleDB/SchaleDB/assets/52343362/7f338e95-2eb9-474b-a89f-b20dac32c0b2)

![캡처_2024_05_01_15_18_57_276](https://github.com/SchaleDB/SchaleDB/assets/52343362/fce9c76e-b539-4d47-a307-78850a5faadf)

2. No range/hit information recently
The recently updated students(starting with Aru(dress)) aren't added information for the range and hit count of their skills.

The 2 issues are neglected for a long time. Please check and fix these, ASAP.

**Comment by lonqie** [comment]
The issue regarding the Railgun characters not being marked as cover users has been fixed. Issue wasn't known/reported to me before today which is why it wasn't fixed until now.

The other issue regarding missing data, this is known but unfortunately as I have not had access to that data since the update that added Dress Aru/Kayoko to the JP client, I have not been able to provide a solution so far.

**Comment by clufox37** [comment]
Got it. Thanks for your work.
